import type { AiOperationalInsight } from './aiInsightsTypes';

/**
 * Mock operational recommendations — replace with API / AI service later.
 * Covers all dashboard insight categories for demo and UX review.
 */
export const MOCK_AI_OPERATIONAL_INSIGHTS: AiOperationalInsight[] = [
  {
    id: 'delay-platform',
    category: 'delayed_project',
    title: 'Platform Development Sprint — schedule slip',
    recommendation:
      'Velocity is 18% below plan for two consecutive sprints. Re-baseline milestones or add a tech lead checkpoint before the 28 May gate.',
    priority: 'critical',
    metric: '4 days',
    metricLabel: 'Behind plan',
    trend: 'down',
    confidence: 91,
    generatedAt: '2 min ago',
    actionLabel: 'Review timeline',
  },
  {
    id: 'delay-data',
    category: 'delayed_project',
    title: 'Data Integration Engine — dependency risk',
    recommendation:
      'Upstream API credentials are blocking integration tests. Escalate to procurement and assign a dedicated unblock owner today.',
    priority: 'high',
    metric: '15%',
    metricLabel: 'Complete',
    trend: 'down',
    confidence: 84,
    generatedAt: '8 min ago',
    actionLabel: 'Open project',
  },
  {
    id: 'prod-week',
    category: 'productivity',
    title: 'Engineering productivity dip detected',
    recommendation:
      'Billable hours per contributor fell 11% week-over-week while meeting load rose. Consider focus blocks and defer non-critical syncs.',
    priority: 'medium',
    metric: '-11%',
    metricLabel: 'vs last week',
    trend: 'down',
    confidence: 78,
    generatedAt: '15 min ago',
    actionLabel: 'View reports',
  },
  {
    id: 'prod-creative',
    category: 'productivity',
    title: 'Creative squad outperforming target',
    recommendation:
      'Brand Re-design Protocol is tracking 9% ahead of forecasted output. Document practices for replication across IT squads.',
    priority: 'low',
    metric: '+9%',
    metricLabel: 'Output index',
    trend: 'up',
    confidence: 72,
    generatedAt: '22 min ago',
  },
  {
    id: 'budget-procurement',
    category: 'budget_risk',
    title: 'Procurement spend approaching Q2 ceiling',
    recommendation:
      'Committed PO value is at 87% of the approved envelope with six weeks remaining. Freeze discretionary purchases or request a variance.',
    priority: 'high',
    metric: '87%',
    metricLabel: 'Budget used',
    trend: 'up',
    confidence: 88,
    generatedAt: '5 min ago',
    actionLabel: 'Expense tracking',
  },
  {
    id: 'budget-mobile',
    category: 'budget_risk',
    title: 'Mobile Messaging — burn rate alert',
    recommendation:
      'Contractor burn is 1.4× planned run-rate given current velocity. Validate scope against SOW or reallocate contingency.',
    priority: 'medium',
    metric: '1.4×',
    metricLabel: 'Burn vs plan',
    trend: 'up',
    confidence: 81,
    generatedAt: '31 min ago',
  },
  {
    id: 'attendance-morning',
    category: 'attendance',
    title: 'Morning attendance gap on operations floor',
    recommendation:
      'Only 62% of scheduled staff clocked in before 09:30 today. Send a pulse check to team leads and review shift coverage.',
    priority: 'high',
    metric: '62%',
    metricLabel: 'On-time clock-in',
    trend: 'down',
    confidence: 86,
    generatedAt: 'Just now',
    actionLabel: 'Team roster',
  },
  {
    id: 'attendance-remote',
    category: 'attendance',
    title: 'Remote workers — session consistency',
    recommendation:
      'Three contributors logged fragmented sessions (<4h total) across the last two days. Align with managers on availability norms.',
    priority: 'medium',
    metric: '3',
    metricLabel: 'Flagged users',
    trend: 'stable',
    confidence: 74,
    generatedAt: '45 min ago',
  },
  {
    id: 'overtime-eng',
    category: 'overtime',
    title: 'Engineering overtime threshold exceeded',
    recommendation:
      'Four engineers are projected to exceed 44h this week. Approve comp time or redistribute load before Friday close.',
    priority: 'critical',
    metric: '44h+',
    metricLabel: 'Projected',
    trend: 'up',
    confidence: 93,
    generatedAt: '3 min ago',
    actionLabel: 'Time tracking',
  },
  {
    id: 'overtime-weekend',
    category: 'overtime',
    title: 'Weekend work pattern emerging',
    recommendation:
      'Off-hours entries increased 23% month-to-date. Review sprint commitments to prevent burnout and compliance exposure.',
    priority: 'high',
    metric: '+23%',
    metricLabel: 'Off-hours',
    trend: 'up',
    confidence: 79,
    generatedAt: '18 min ago',
  },
  {
    id: 'forecast-mobile',
    category: 'forecast',
    title: 'Mobile Messaging — early completion likely',
    recommendation:
      'Current burndown suggests 90% confidence of delivery by 24 May, 3 days ahead of baseline. Prepare UAT handoff resources.',
    priority: 'low',
    metric: '24 May',
    metricLabel: 'Forecast finish',
    trend: 'up',
    confidence: 90,
    generatedAt: '12 min ago',
    actionLabel: 'Project board',
  },
  {
    id: 'forecast-platform',
    category: 'forecast',
    title: 'Platform sprint — completion window widening',
    recommendation:
      'Monte-carlo style mock forecast places P50 completion at 2 Jun (+5 days). Communicate revised date to stakeholders this week.',
    priority: 'medium',
    metric: '2 Jun',
    metricLabel: 'P50 date',
    trend: 'down',
    confidence: 85,
    generatedAt: '27 min ago',
    actionLabel: 'Share update',
  },
];
