import type { LiveFieldOpsSnapshot } from './liveFieldOpsTypes';

export function buildLiveFieldOpsSnapshot(): LiveFieldOpsSnapshot {
  return {
    updatedAt: new Date().toISOString(),
    metrics: [
      {
        id: 'teams',
        label: 'Active field teams',
        value: 7,
        display: '7',
        state: 'optimal',
        delta: '+2 vs yesterday',
        deltaUp: true,
        sparkline: [4, 5, 5, 6, 6, 7, 7, 7],
        gps: { lat: -26.2041, lng: 28.0473, label: 'Gauteng corridor' },
        pulseHz: 1.2,
      },
      {
        id: 'visits',
        label: 'Live site visits',
        value: 12,
        display: '12',
        state: 'optimal',
        delta: '4 completing now',
        deltaUp: true,
        sparkline: [6, 8, 9, 10, 11, 12, 11, 12],
        gps: { lat: -33.9249, lng: 18.4241, label: 'Cape Town metro' },
        pulseHz: 1.8,
      },
      {
        id: 'offsite',
        label: 'Staff offsite',
        value: 24,
        display: '24',
        state: 'neutral',
        delta: '68% of field roster',
        deltaUp: true,
        sparkline: [18, 19, 21, 22, 23, 24, 24, 24],
      },
      {
        id: 'installations',
        label: 'Active installations',
        value: 5,
        display: '5',
        state: 'optimal',
        delta: '2 handoffs today',
        deltaUp: true,
        sparkline: [2, 3, 3, 4, 4, 5, 5, 5],
        gps: { lat: -29.8587, lng: 31.0218, label: 'Durban industrial' },
        pulseHz: 0.9,
      },
      {
        id: 'issues',
        label: 'Unresolved field issues',
        value: 3,
        display: '3',
        state: 'watch',
        delta: '1 SLA breach risk',
        deltaUp: false,
        sparkline: [1, 2, 2, 3, 4, 3, 3, 3],
      },
      {
        id: 'late-checkins',
        label: 'Late check-ins',
        value: 2,
        display: '2',
        state: 'critical',
        delta: '+18 min avg delay',
        deltaUp: false,
        sparkline: [0, 1, 1, 2, 3, 2, 2, 2],
        gps: { lat: -25.7479, lng: 28.2293, label: 'Pretoria east' },
      },
      {
        id: 'route-delays',
        label: 'Route delays',
        value: 4,
        display: '4',
        state: 'watch',
        delta: 'Heavy traffic · N1',
        deltaUp: false,
        sparkline: [2, 3, 2, 4, 5, 4, 4, 4],
        gps: { lat: -26.1076, lng: 28.0567, label: 'N1 corridor' },
      },
      {
        id: 'travel',
        label: 'Active travel time',
        value: 222,
        display: '3h 42m',
        state: 'neutral',
        delta: '-12 min vs plan',
        deltaUp: true,
        sparkline: [280, 265, 250, 240, 235, 228, 222, 222],
      },
      {
        id: 'availability',
        label: 'Workforce availability',
        value: 87,
        display: '87',
        suffix: '%',
        state: 'optimal',
        delta: '6 on standby',
        deltaUp: true,
        sparkline: [82, 83, 84, 85, 86, 87, 87, 87],
      },
    ],
    pulses: [
      { id: 'p1', label: '08:00', intensity: 42, state: 'neutral' },
      { id: 'p2', label: '09:00', intensity: 58, state: 'optimal' },
      { id: 'p3', label: '10:00', intensity: 71, state: 'optimal' },
      { id: 'p4', label: '11:00', intensity: 88, state: 'optimal' },
      { id: 'p5', label: '12:00', intensity: 65, state: 'watch' },
      { id: 'p6', label: '13:00', intensity: 79, state: 'optimal' },
      { id: 'p7', label: 'Now', intensity: 94, state: 'optimal' },
    ],
    activeRegions: [
      { name: 'Johannesburg CBD', crews: 3, state: 'optimal' },
      { name: 'Sandton installs', crews: 2, state: 'optimal' },
      { name: 'Cape logistics', crews: 2, state: 'watch' },
      { name: 'Durban port run', crews: 1, state: 'neutral' },
    ],
  };
}
